version: '3'

services:
  kafka-mailgun:
    build: .
    image: kafka-mailgun
    environment:
    - MAILGUN_API_KEY=${MAILGUN_API_KEY}
    - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
    - MAILGUN_VARIABLES=${MAILGUN_VARIABLES}
    - CONFLUENT_ENABLE=${CONFLUENT_ENABLE}
    - CONFLUENT_BOOTSTRAP=${CONFLUENT_BOOTSTRAP}
    - CONFLUENT_API_KEY=${CONFLUENT_API_KEY}
    - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
    - KAFKA_BROKER=${KAFKA_BROKER}
    - KAFKA_TOPIC=${KAFKA_TOPIC}
    - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
    - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
    - PORT=${PORT}
    - TEMPLATES_DIR=${TEMPLATES_DIR}
